[project]
name = "bids-guidelines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docopt>=0.6.2",
    "pybids>=0.19.0",
]

[dependency-groups]
dev = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
]
